server:
  port: 8989

spring:
  datasource:
    db1:
      driver-class-name: org.sqlite.JDBC
      jdbc-url: jdbc:sqlite:H:/data/panoramaTW/OSM/taiwan.mbtiles
    db2:
      driver-class-name: org.sqlite.JDBC
      jdbc-url: jdbc:sqlite:H:/data/panoramaTW/googleImage/Data-rout.gmdb
    db3:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5432/panoramaTW
      username: postgres
      password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml

path:
  temp: H:\data\nearshore\temp
  rasterTile: H:\data\nearshore\raster\rasterTile
  rasterFile: H:\data\nearshore\raster\rasterFile
  static: H:\data\nearshore\static
  3DTile: H:\data\nearshore\3DTile