server:
  port: 8765

spring:
  data:
    mongodb:
      database: east
      authentication-database: admin
      uri: mongodb://localhost:27017/east
  datasource:
    default:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/east
      username: postgres
      password: 123456
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB

path:
  temp: E:\data\nearshore\temp
  rasterTile: E:\data\nearshore\raster\rasterTile
  rasterFile: E:\data\nearshore\raster\rasterFile
  static: E:\data\nearshore\static
  3DTile: E:\data\nearshore\3DTile

