server:
  port: 9876

spring:
  data:
    mongodb:
      database: panoramaTW
      authentication-database: admin
      uri: mongodb://mongo:27017/panoramaTW
  datasource:
    default:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://pg:5432/panoramaTW
      username: postgres
      password: 123456
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB

path:
  script: /data/panoramaTW/script/
  temp: /data/panoramaTW/temp
  rasterTile: H:\data\nearshore\raster\rasterTile
  rasterFile: H:\data\nearshore\raster\rasterFile
  static: H:\data\nearshore\static
  3DTile: H:\data\nearshore\3DTile

